### ISSUE TITLE
Error loading config.yaml

### ISSUE THREAD

**Issue by sandstad** [security-automation/crits-adapter#6]
[root@localhost crits]# service edgy_critsd start
starting edgy_critsd...
/opt/soltra/edge/lib/python2.7/site-packages/setuptools-6.0.2-py2.7.egg/pkg_resources.py:1032: UserWarning: /opt/soltra/edge/var/repository/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Traceback (most recent call last):
  File "/opt/soltra/edge/repository/adapters/crits/edgy_critsd.py", line 77, in <module>
    main()
  File "/opt/soltra/edge/repository/adapters/crits/edgy_critsd.py", line 57, in main
    config = util_.parse_config(args['--config'])
  File "./lib_/util_.py", line 81, in parse_config
    return(yaml.safe_load(file(file_, 'r')))
IOError: [Errno 13] Permission denied: '/opt/soltra/edge/repository/adapters/crits/config.yaml'

**Comment by treyka** [comment]
Hi, @sandstad -

The edgy_critsd service is configured to run as the same user as Edge does ('repo', by default). It looks like you installed all the adapter bits as root. Try this:

* `chown -R repo.repo /opt/soltra/edge/repository/adapters/crits/`
* `chmod -R ug+rw /opt/soltra/edge/repository/adapters/crits/`
* `find /opt/soltra/edge/repository/adapters/crits/ -type d -exec chmod a+x {} \;`
* `service edgy_critsd restart`

That should fix things; please confirm and I'll modify the adapter setup.sh to double-check perms at install time.

Cheers!
